version: '3'
services:
  nginx:
    container_name: nginx-dev
    build:
      context: ./services/nginx
      args:
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        NGINX_VERSION: nginx:${NGINX_VERSION}
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    volumes:
      - "./services/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./services/nginx/conf.d:/etc/nginx/conf.d"
      - "./logs/nginx:/var/log/nginx"
      - "./www:${APP_DIR}/default_app"
      - "${WORKSHOP_DIR}:${APP_DIR}:rw"
    environment:
      TZ: "${TZ}"
    restart: always
    links:
      - php72
  php72:
    container_name: php72-dev
    build:
      context: ./services/php72
      args:
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        PHP_VERSION: php:${PHP72_VERSION}
        PHP_EXTENSIONS: ${PHP72_EXTENSIONS}
    volumes:
      - "./services/php72/php.ini:/usr/local/etc/php/php.ini"
      - "./services/php72/php-fpm.conf:/usr/local/etc/php-fpm.conf"
      - "./services/php72/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf"
      - "./www:${APP_DIR}/default_app"
      - "${WORKSHOP_DIR}:${APP_DIR}:rw"
    restart: always
    links:
      - mysql
  redis:
    container_name: redis-dev
    image: redis:${REDIS_VERSION}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - "./services/redis/redis.conf:/etc/redis.conf"
      - "${DATA_DIR}/redis:/data:rw"
    restart: always
  mysql:
    container_name: mysql-dev
    image: mysql:${MYSQL_VERSION}
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "${MYSQL_PORT}:3306"
    restart: always
  golang:
    container_name: golang-dev
    image: golang:${GO_VERSION}
    environment: 
      GO111MODULE: "on"
      GOPROXY: "https://goproxy.cn"
    volumes:
      - ./services/go/http.go:/http.go
      - ${WORKSHOP_DIR}/go:/go
    ports:
      - "${GO_PORT}:8080"
    command: go run /http.go