version: '3'
services:
  golang:
    container_name: golang-dev
    image: golang:1.15.4-alpine
    environment: 
      GO111MODULE: "on"
      GOPROXY: "https://goproxy.cn"
    volumes:
      - ./services/go/http.go:/http.go
      - ${WORKSHOP_DIR}/go:/go
    ports:
      - "18080:18080"
    command: go run /http.go
  nginx:
    depends_on:
      - php72
    container_name: nginx-dev
    image: nginx:1.15.7-alpine
    environment:
      TZ: "Asia/Shanghai"
    ports:
      - "18085:80"
    volumes:
      - "./services/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./services/nginx/conf.d:/etc/nginx/conf.d"
      - "./logs/nginx:/var/log/nginx"
      - "./www:/home/www"
    restart: always
    links:
      - php72
  php72:
    container_name: php72-dev
    image: php:7.2.0-fpm-alpine
    volumes:
      - "./services/php72/php.ini:/usr/local/etc/php/php.ini"
      - "./services/php72/php-fpm.conf:/usr/local/etc/php-fpm.conf"
      - "./services/php72/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf"
      - "./www:/home/www"
    restart: always
  redis:
    container_name: redis-dev
    image: redis:6.0-alpine
    restart: always
    ports:
      - "18095:6379"
  mysql:
    container_name: mysql-dev
    image: mysql:5.7.32
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    ports:
      - "18100:3306"